<?php
require __DIR__.'/includes/bootstrap.php';require_admin();$pdo=db();$message='';$error='';
function upgrade_column_exists(PDO $pdo,string $table,string $column): bool {$s=$pdo->prepare('SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=? AND COLUMN_NAME=?');$s->execute([$table,$column]);return (int)$s->fetchColumn()>0;}
function upgrade_index_exists(PDO $pdo,string $table,string $index): bool {$s=$pdo->prepare('SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=? AND INDEX_NAME=?');$s->execute([$table,$index]);return (int)$s->fetchColumn()>0;}
function upgrade_add_column(PDO $pdo,string $table,string $column,string $definition): void {if(!upgrade_column_exists($pdo,$table,$column))$pdo->exec("ALTER TABLE `{$table}` ADD COLUMN `{$column}` {$definition}");}
function upgrade_run_sql(PDO $pdo,string $file): void {$sql=(string)file_get_contents($file);$sql=preg_replace('/^\s*--.*$/m','',$sql)??$sql;foreach(preg_split('/;\s*(?:\r?\n|$)/',$sql)?:[] as $statement){$statement=trim($statement);if($statement!=='')$pdo->exec($statement);}}
if($_SERVER['REQUEST_METHOD']==='POST'){
  check_csrf();
  try{
    upgrade_add_column($pdo,'countries','source_url','VARCHAR(1000) NULL AFTER uncitral_status');upgrade_add_column($pdo,'countries','last_verified_at','DATE NULL AFTER source_url');
    $docColumns=[
      'language_code'=>"CHAR(2) NOT NULL DEFAULT 'en' AFTER document_type",'document_number'=>'VARCHAR(120) NULL AFTER language_code','version_label'=>'VARCHAR(100) NULL AFTER year',
      'legal_status'=>"ENUM('current','amended','repealed','superseded','draft') NOT NULL DEFAULT 'current' AFTER version_label",'effective_date'=>'DATE NULL AFTER legal_status','repeal_date'=>'DATE NULL AFTER effective_date','last_verified_at'=>'DATE NULL AFTER repeal_date','verification_source'=>'VARCHAR(1000) NULL AFTER last_verified_at','verification_notes'=>'TEXT NULL AFTER verification_source','supersedes_document_id'=>'BIGINT UNSIGNED NULL AFTER verification_notes','repealed_by_document_id'=>'BIGINT UNSIGNED NULL AFTER supersedes_document_id'
    ];foreach($docColumns as $column=>$definition)upgrade_add_column($pdo,'documents',$column,$definition);
    upgrade_add_column($pdo,'cases','language_code',"CHAR(2) NOT NULL DEFAULT 'en' AFTER country_id");upgrade_add_column($pdo,'cases','last_verified_at','DATE NULL AFTER source_url');
    upgrade_add_column($pdo,'institutions','language_code',"CHAR(2) NOT NULL DEFAULT 'en' AFTER country_id");upgrade_add_column($pdo,'institutions','last_verified_at','DATE NULL AFTER rules_url');
    upgrade_run_sql($pdo,__DIR__.'/database/schema.sql');upgrade_run_sql($pdo,__DIR__.'/database/seed.sql');
    $versionColumns=[
      'country_id'=>'SMALLINT UNSIGNED NULL AFTER revision_no','regime_key'=>'VARCHAR(40) NULL AFTER country_id','section_key'=>"VARCHAR(80) NOT NULL DEFAULT 'national-legislation' AFTER regime_key",'year'=>'SMALLINT UNSIGNED NULL AFTER summary','supersedes_document_id'=>'BIGINT UNSIGNED NULL AFTER verification_notes','repealed_by_document_id'=>'BIGINT UNSIGNED NULL AFTER supersedes_document_id','is_published'=>'TINYINT(1) NOT NULL DEFAULT 0 AFTER file_size','published_at'=>'DATETIME NULL AFTER is_published'
    ];foreach($versionColumns as $column=>$definition)upgrade_add_column($pdo,'document_versions',$column,$definition);
    if(!upgrade_index_exists($pdo,'documents','idx_documents_legal_status'))$pdo->exec('ALTER TABLE documents ADD INDEX idx_documents_legal_status(legal_status)');
    if(!upgrade_index_exists($pdo,'documents','idx_documents_effective_date'))$pdo->exec('ALTER TABLE documents ADD INDEX idx_documents_effective_date(effective_date)');
    if(!upgrade_index_exists($pdo,'document_versions','idx_version_country'))$pdo->exec('ALTER TABLE document_versions ADD INDEX idx_version_country(country_id)');
    if(!upgrade_index_exists($pdo,'document_versions','idx_version_legal_status'))$pdo->exec('ALTER TABLE document_versions ADD INDEX idx_version_legal_status(legal_status)');
    activity('database_upgraded','Multilingual, legal lifecycle, research folders and institutional subscription upgrade');$message='Database upgrade completed successfully. Delete or rename upgrade.php after deployment.';
  }catch(Throwable $e){$error=$e->getMessage();}
}
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Upgrade | African Disputes Resolution</title><link rel="icon" type="image/svg+xml" href="<?=url('assets/favicon.svg')?>"><link rel="icon" href="<?=url('favicon.ico')?>" sizes="any"><link rel="icon" type="image/png" href="<?=url('assets/favicon-128.png')?>"><link rel="stylesheet" href="<?=url('assets/style.css')?>"><link rel="stylesheet" href="<?=url('assets/admin.css')?>"></head><body><main><section class="page-hero"><div class="container"><span class="eyebrow">One-time database migration</span><h1>Upgrade African Disputes Resolution</h1><p>Add multilingual metadata, legal document history, verification dates, research folders and institutional subscriptions to an existing installation.</p></div></section><section class="section"><div class="narrow"><?php if($message):?><div class="flash success"><div><?=e($message)?></div></div><?php endif;?><?php if($error):?><div class="flash error"><div><?=e($error)?></div></div><?php endif;?><form class="form-card" method="post"><?=csrf_field()?><h2>Run database upgrade</h2><p>Back up the database and <code>storage/uploads</code> first. The migration is repeat-safe and does not delete existing records.</p><button>Run upgrade</button><a class="button dark-btn" href="<?=url('admin.php')?>">Back to admin</a></form></div></section></main></body></html>
