INSERT INTO countries(code,name,region,common_law_index) VALUES
('DZA','Algeria','Northern Africa',0),
('AGO','Angola','Central Africa',0),
('BEN','Benin','Western Africa',0),
('BWA','Botswana','Southern Africa',1),
('BFA','Burkina Faso','Western Africa',0),
('BDI','Burundi','Eastern Africa',0),
('CMR','Cameroon','Central Africa',0),
('CPV','Cape Verde','Western Africa',0),
('CAF','Central African Republic','Central Africa',0),
('TCD','Chad','Central Africa',0),
('COM','Comoros','Eastern Africa',0),
('CIV','Côte d’Ivoire','Western Africa',0),
('COD','Democratic Republic of Congo','Central Africa',0),
('DJI','Djibouti','Eastern Africa',0),
('EGY','Egypt','Northern Africa',0),
('GNQ','Equatorial Guinea','Central Africa',0),
('ERI','Eritrea','Eastern Africa',0),
('SWZ','Eswatini','Southern Africa',1),
('ETH','Ethiopia','Eastern Africa',0),
('GAB','Gabon','Central Africa',0),
('GHA','Ghana','Western Africa',1),
('GIN','Guinea','Western Africa',0),
('GNB','Guinea-Bissau','Western Africa',0),
('KEN','Kenya','Eastern Africa',1),
('LSO','Lesotho','Southern Africa',1),
('LBR','Liberia','Western Africa',1),
('LBY','Libya','Northern Africa',0),
('MDG','Madagascar','Eastern Africa',0),
('MWI','Malawi','Eastern Africa',1),
('MLI','Mali','Western Africa',0),
('MRT','Mauritania','Western Africa',0),
('MUS','Mauritius','Eastern Africa',1),
('MAR','Morocco','Northern Africa',0),
('MOZ','Mozambique','Southern Africa',0),
('NAM','Namibia','Southern Africa',1),
('NER','Niger','Western Africa',0),
('NGA','Nigeria','Western Africa',1),
('COG','Republic of Congo','Central Africa',0),
('RWA','Rwanda','Eastern Africa',0),
('STP','São Tomé & Príncipe','Central Africa',0),
('SEN','Senegal','Western Africa',0),
('SYC','Seychelles','Eastern Africa',1),
('SLE','Sierra Leone','Western Africa',1),
('SOM','Somalia','Eastern Africa',0),
('ZAF','South Africa','Southern Africa',1),
('SSD','South Sudan','Eastern Africa',0),
('GMB','The Gambia','Western Africa',1),
('SDN','The Sudan','Northern Africa',1),
('TGO','Togo','Western Africa',0),
('TUN','Tunisia','Northern Africa',0),
('UGA','Uganda','Eastern Africa',1),
('TZA','United Republic of Tanzania','Eastern Africa',1),
('ZMB','Zambia','Southern Africa',1),
('ZWE','Zimbabwe','Southern Africa',1)
ON DUPLICATE KEY UPDATE name=VALUES(name),region=VALUES(region),common_law_index=VALUES(common_law_index);

INSERT INTO subscription_plans(code,name,description,annual_price,currency,included_seats,features,is_active,sort_order) VALUES
('professional','Professional','For law firms, chambers and ADR practices that need shared research access.',1200.00,'USD',10,'Shared research folders\nCitation exports\nPriority editorial updates\nUsage support',1,10),
('academic','Academic','For universities, law schools, libraries and research centres.',1800.00,'USD',30,'Campus research access\nShared folders\nCitation exports\nTraining session\nUsage reporting',1,20),
('enterprise','Enterprise','For courts, public bodies, development institutions and large organisations.',NULL,'USD',100,'Custom seat allocation\nOrganisation onboarding\nPriority support\nData and integration consultation\nCustom reporting',1,30)
ON DUPLICATE KEY UPDATE code=VALUES(code);
